verbose: true
device: "mps"

llama_config:
  model_name: "meta-llama/Meta-Llama-3-8B-Instruct"
  system_prompt: "You are a helpful assistant"
  max_num_historical_messages: 6
  max_tokens: 256
  temperature: 0.7
  top_p: 0.9

sd_config:
  root_models_path: /Users/ahestevenz/.cache/huggingface/hub
  root_output_dir: /Users/ahestevenz/Desktop/hola
  model_type: "sd_1_5_img_2_img"
  model_paths:
    sd_3:
      - models--stabilityai--stable-diffusion-3-medium-diffusers/sd3_medium_incl_clips_t5xxlfp16.safetensors
      - models--Stable-Diffusion-XL/sd_xl_refiner_1.0.safetensors
    sd_xl:
      - models--Stable-Diffusion-XL/sd_xl_base_1.0.safetensors
      - models--Stable-Diffusion-XL/sd_xl_refiner_1.0.safetensors
    civitai:
      - models--civitai/juggernautXL_juggXIByRundiffusion.safetensors
      - models--Stable-Diffusion-XL/sd_xl_refiner_1.0.safetensors
    pix_2_pix:
      - models--timbrooks--instruct-pix2pix/snapshots/31519b5cb02a7fd89b906d88731cd4d6a7bbf88d
      - null
    sd_1_5_img_2_img:
      - models--radames--stable-diffusion-v1-5-img2img/snapshots/cac24f945bd8f5604e243550bb3092be11964805
      - null
